#### CSV dan Data

In [1]:
# Khusus Buat File CSV
import numpy as np
import pandas as pd

In [2]:
headernya='label,0.1,02,0.3'
arr2D = np.array([ [0, 12, 13, 22],
                   [0, 7, 23, 14],
                   [0, 10, 33, 7],
                   [0, 7, 23, 14],
                   [0, 10, 33, 7],
                   [0, 7, 23, 14],
                   [0, 10, 33, 7],
                   [0, 7, 23, 14],
                   [0, 10, 33, 7],
                   [0, 7, 23, 14],
                   [0, 10, 33, 7],
                   [0, 7, 23, 14],
                   [0, 10, 33, 7],
                   [1, 7, 23, 14],
                   [1, 10, 33, 7],
                   [1, 7, 23, 14],
                   [1, 10, 33, 7],
                   [1, 7, 23, 14],
                   [1, 10, 33, 7],
                   [2, 7, 23, 14],
                   [2, 10, 33, 7],
                   [2, 7, 23, 14],
                   [2, 10, 33, 7],
                   [2, 7, 23, 14],
                   [2, 10, 33, 7],
                   [2, 7, 23, 14],
                   [3, 10, 33, 7],
                   [3, 7, 23, 14],
                   [3, 10, 33, 7],
                   [3, 7, 23, 14],
                   [3, 10, 33, 7],
                   [3, 7, 23, 14],
                   [3, 10, 33, 7],
                   [3, 7, 23, 14],
                   [3, 10, 33, 7],
                 ])

In [3]:
# Save 2D numpy array to csv file
np.savetxt('2darray.csv', arr2D, delimiter=',', header = headernya ,fmt='%d')

In [23]:
#data45 = np.genfromtxt('2darray.csv', delimiter = ',')
#print(data45)
data45 = pd.read_csv('2darray.csv').astype('int')
data45.rename(columns={'0':'# label'}, inplace=True)
print(data45)

    # label  0.1  02  0.3
0         0   12  13   22
1         0    7  23   14
2         0   10  33    7
3         0    7  23   14
4         0   10  33    7
5         0    7  23   14
6         0   10  33    7
7         0    7  23   14
8         0   10  33    7
9         0    7  23   14
10        0   10  33    7
11        0    7  23   14
12        0   10  33    7
13        1    7  23   14
14        1   10  33    7
15        1    7  23   14
16        1   10  33    7
17        1    7  23   14
18        1   10  33    7
19        2    7  23   14
20        2   10  33    7
21        2    7  23   14
22        2   10  33    7
23        2    7  23   14
24        2   10  33    7
25        2    7  23   14
26        3   10  33    7
27        3    7  23   14
28        3   10  33    7
29        3    7  23   14
30        3   10  33    7
31        3    7  23   14
32        3   10  33    7
33        3    7  23   14
34        3   10  33    7


In [24]:
dx_kar = data45.drop('# label',axis = 1)
dy_kar = data45['# label']

In [25]:
from sklearn.model_selection import train_test_split
dxds_train, dxds_test, dyds_train, dyds_test = train_test_split(dx_kar,dy_kar)

In [26]:
dxds_train.shape, dxds_test.shape, dyds_train.shape, dyds_test.shape

((26, 3), (9, 3), (26,), (9,))

In [27]:
print(dxds_train)

    0.1  02  0.3
23    7  23   14
11    7  23   14
9     7  23   14
26   10  33    7
27    7  23   14
33    7  23   14
12   10  33    7
17    7  23   14
24   10  33    7
34   10  33    7
30   10  33    7
4    10  33    7
7     7  23   14
2    10  33    7
29    7  23   14
19    7  23   14
28   10  33    7
31    7  23   14
20   10  33    7
15    7  23   14
0    12  13   22
5     7  23   14
13    7  23   14
6    10  33    7
16   10  33    7
14   10  33    7


In [28]:
from sklearn.preprocessing import MinMaxScaler
standard_scaler = MinMaxScaler()
standard_scaler.fit(dxds_train)

MinMaxScaler()

In [29]:
dxds_train = standard_scaler.transform(dxds_train)
dxds_test  = standard_scaler.transform(dxds_test)

In [35]:
print(dxds_train)

[[0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [1.         0.         1.        ]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]]


In [30]:
dxds_train = dxds_train.reshape(dxds_train.shape[0], 1, 3).astype('float32')
dxds_test  = dxds_test.reshape(dxds_test.shape[0], 1, 3).astype('float32')

In [31]:
dxds_train.shape, dxds_test.shape, dyds_train.shape, dyds_test.shape

((26, 1, 3), (9, 1, 3), (26,), (9,))

In [32]:
dxds_train = dxds_train.reshape((-1, 3))

In [33]:
dxds_test = dxds_test.reshape((-1, 3))

In [34]:
dxds_train.shape, dxds_test.shape

((26, 3), (9, 3))

In [18]:
import tensorflow as tf
dyds_train = tf.keras.utils.to_categorical(dyds_train)
dyds_test  = tf.keras.utils.to_categorical(dyds_test)

In [19]:
dxds_train.shape, dxds_test.shape, dyds_train.shape, dyds_test.shape

((26, 3), (9, 3), (26, 4), (9, 4))

In [20]:
print(dxds_train.min(), "-", dxds_train.max())

0.0 - 1.0


In [21]:
print(dxds_train)

[[0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.         0.5        0.46666667]
 [0.6        1.         0.        ]
 [0.6        1.         0.        ]
 [1.         0.         1.        ]]
